window.esdocSearchIndex = [
  [
    "@aureooms/js-integer-big-endian/src/core/thresholds/division.js~threshold_div_dc",
    "variable/index.html#static-variable-THRESHOLD_DIV_DC",
    "<span>THRESHOLD_DIV_DC</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/thresholds/division.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/thresholds/multiplication.js~threshold_mul_toom22",
    "variable/index.html#static-variable-THRESHOLD_MUL_TOOM22",
    "<span>THRESHOLD_MUL_TOOM22</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/thresholds/multiplication.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/add/_add.js~_add",
    "function/index.html#static-function-_ADD",
    "<span>_ADD</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/add/_ADD.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_cmp.js~_cmp",
    "function/index.html#static-function-_CMP",
    "<span>_CMP</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_CMP.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_cmp_n.js~_cmp_n",
    "function/index.html#static-function-_CMP_n",
    "<span>_CMP_n</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_CMP_n.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/add/_iadd.js~_iadd",
    "function/index.html#static-function-_IADD",
    "<span>_IADD</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/add/_IADD.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/array/_alloc.js~_alloc",
    "function/index.html#static-function-_alloc",
    "<span>_alloc</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/array/_alloc.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/array/_build.js~_build",
    "function/index.html#static-function-_build",
    "<span>_build</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/array/_build.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_chr.js~_chr",
    "function/index.html#static-function-_chr",
    "<span>_chr</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_chr.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_cmp.js~_cmp",
    "function/index.html#static-function-_cmp",
    "<span>_cmp</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_cmp.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_convert.js~_convert",
    "function/index.html#static-function-_convert",
    "<span>_convert</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_convert.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_convert_slow.js~_convert_slow",
    "function/index.html#static-function-_convert_slow",
    "<span>_convert_slow</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_convert_slow.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_convert_to_larger.js~_convert_to_larger",
    "function/index.html#static-function-_convert_to_larger",
    "<span>_convert_to_larger</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_convert_to_larger.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_convert_to_larger_fast.js~_convert_to_larger_fast",
    "function/index.html#static-function-_convert_to_larger_fast",
    "<span>_convert_to_larger_fast</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_convert_to_larger_fast.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_convert_to_smaller.js~_convert_to_smaller",
    "function/index.html#static-function-_convert_to_smaller",
    "<span>_convert_to_smaller</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_convert_to_smaller.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_convert_to_smaller_fast.js~_convert_to_smaller_fast",
    "function/index.html#static-function-_convert_to_smaller_fast",
    "<span>_convert_to_smaller_fast</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_convert_to_smaller_fast.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/array/_copy.js~_copy",
    "function/index.html#static-function-_copy",
    "<span>_copy</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/array/_copy.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/sub/_decrement.js~_decrement",
    "function/index.html#static-function-_decrement",
    "<span>_decrement</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/sub/_decrement.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_div_limb_with_prefix.js~_div_limb_with_prefix",
    "function/index.html#static-function-_div_limb_with_prefix",
    "<span>_div_limb_with_prefix</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_div_limb_with_prefix.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/api/_divmod.js~_divmod",
    "function/index.html#static-function-_divmod",
    "<span>_divmod</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/api/_divmod.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_eq.js~_eq",
    "function/index.html#static-function-_eq",
    "<span>_eq</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_eq.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/gcd/_euclidean_algorithm.js~_euclidean_algorithm",
    "function/index.html#static-function-_euclidean_algorithm",
    "<span>_euclidean_algorithm</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/gcd/_euclidean_algorithm.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/gcd/_extended_euclidean_algorithm.js~_extended_euclidean_algorithm",
    "function/index.html#static-function-_extended_euclidean_algorithm",
    "<span>_extended_euclidean_algorithm</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/gcd/_extended_euclidean_algorithm.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/array/_fill.js~_fill",
    "function/index.html#static-function-_fill",
    "<span>_fill</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/array/_fill.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_ge.js~_ge",
    "function/index.html#static-function-_ge",
    "<span>_ge</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_ge.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_gt.js~_gt",
    "function/index.html#static-function-_gt",
    "<span>_gt</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_gt.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/api/_idivmod.js~_idivmod",
    "function/index.html#static-function-_idivmod",
    "<span>_idivmod</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/api/_idivmod.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_dc.js~_idivmod_dc",
    "function/index.html#static-function-_idivmod_dc",
    "<span>_idivmod_dc</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_dc.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_dc_21.js~_idivmod_dc_21",
    "function/index.html#static-function-_idivmod_dc_21",
    "<span>_idivmod_dc_21</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_dc_21.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_dc_32.js~_idivmod_dc_32",
    "function/index.html#static-function-_idivmod_dc_32",
    "<span>_idivmod_dc_32</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_dc_32.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_limb.js~_idivmod_limb",
    "function/index.html#static-function-_idivmod_limb",
    "<span>_idivmod_limb</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_limb.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_limb_with_prefix.js~_idivmod_limb_with_prefix",
    "function/index.html#static-function-_idivmod_limb_with_prefix",
    "<span>_idivmod_limb_with_prefix</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_limb_with_prefix.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_schoolbook.js~_idivmod_schoolbook",
    "function/index.html#static-function-_idivmod_schoolbook",
    "<span>_idivmod_schoolbook</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_schoolbook.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_schoolbook_large_divisor.js~_idivmod_schoolbook_large_divisor",
    "function/index.html#static-function-_idivmod_schoolbook_large_divisor",
    "<span>_idivmod_schoolbook_large_divisor</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_schoolbook_large_divisor.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_schoolbook_subroutine.js~_idivmod_schoolbook_subroutine",
    "function/index.html#static-function-_idivmod_schoolbook_subroutine",
    "<span>_idivmod_schoolbook_subroutine</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_schoolbook_subroutine.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_slow.js~_idivmod_slow",
    "function/index.html#static-function-_idivmod_slow",
    "<span>_idivmod_slow</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_idivmod_slow.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_imul_limb.js~_imul_limb",
    "function/index.html#static-function-_imul_limb",
    "<span>_imul_limb</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_imul_limb.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/add/_increment.js~_increment",
    "function/index.html#static-function-_increment",
    "<span>_increment</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/add/_increment.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_int.js~_int",
    "function/index.html#static-function-_int",
    "<span>_int</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_int.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/sub/_isub.js~_isub",
    "function/index.html#static-function-_isub",
    "<span>_isub</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/sub/_isub.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_jz.js~_jz",
    "function/index.html#static-function-_jz",
    "<span>_jz</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_jz.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_karatsuba.js~_karatsuba",
    "function/index.html#static-function-_karatsuba",
    "<span>_karatsuba</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_karatsuba.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_le.js~_le",
    "function/index.html#static-function-_le",
    "<span>_le</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_le.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_log.js~_log",
    "function/index.html#static-function-_log",
    "<span>_log</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_log.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_lt.js~_lt",
    "function/index.html#static-function-_lt",
    "<span>_lt</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_lt.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/div/_mod_limb.js~_mod_limb",
    "function/index.html#static-function-_mod_limb",
    "<span>_mod_limb</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/div/_mod_limb.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_mul.js~_mul",
    "function/index.html#static-function-_mul",
    "<span>_mul</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_mul_limb.js~_mul_limb",
    "function/index.html#static-function-_mul_limb",
    "<span>_mul_limb</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_mul_limb.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/compare/_ne.js~_ne",
    "function/index.html#static-function-_ne",
    "<span>_ne</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/compare/_ne.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/pow/_powd.js~_powd",
    "function/index.html#static-function-_powd",
    "<span>_powd</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/pow/_powd.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/array/_reset.js~_reset",
    "function/index.html#static-function-_reset",
    "<span>_reset</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/array/_reset.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_schoolbook_mul.js~_schoolbook_mul",
    "function/index.html#static-function-_schoolbook_mul",
    "<span>_schoolbook_mul</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_schoolbook_mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/sub/_sub.js~_sub",
    "function/index.html#static-function-_sub",
    "<span>_sub</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/sub/_sub.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_to_string.js~_to_string",
    "function/index.html#static-function-_to_string",
    "<span>_to_string</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_to_string.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_toom22.js~_toom22",
    "variable/index.html#static-variable-_toom22",
    "<span>_toom22</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/arithmetic/mul/_toom22.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/_trim_positive.js~_trim_positive",
    "function/index.html#static-function-_trim_positive",
    "<span>_trim_positive</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/_trim_positive.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/array/_zeros.js~_zeros",
    "function/index.html#static-function-_zeros",
    "<span>_zeros</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/array/_zeros.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/api/add.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/api/add.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/convert.js~convert",
    "function/index.html#static-function-convert",
    "<span>convert</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/convert.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/convert_keep_zeros.js~convert_keep_zeros",
    "function/index.html#static-function-convert_keep_zeros",
    "<span>convert_keep_zeros</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/convert_keep_zeros.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/api/iadd.js~iadd",
    "function/index.html#static-function-iadd",
    "<span>iadd</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/api/iadd.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/api/mul.js~mul",
    "function/index.html#static-function-mul",
    "<span>mul</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/api/mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/parse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/parse_keep_zeros.js~parse_keep_zeros",
    "function/index.html#static-function-parse_keep_zeros",
    "<span>parse_keep_zeros</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/parse_keep_zeros.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/stringify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/stringify_keep_zeros.js~stringify_keep_zeros",
    "function/index.html#static-function-stringify_keep_zeros",
    "<span>stringify_keep_zeros</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/stringify_keep_zeros.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/translate.js~translate",
    "function/index.html#static-function-translate",
    "<span>translate</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/translate.js</span>",
    "function"
  ],
  [
    "@aureooms/js-integer-big-endian/src/core/convert/trim_natural.js~trim_natural",
    "function/index.html#static-function-trim_natural",
    "<span>trim_natural</span> <span class=\"search-result-import-path\">@aureooms/js-integer-big-endian/src/core/convert/trim_natural.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/api/_divmod.js",
    "file/src/api/_divmod.js.html",
    "src/api/_divmod.js",
    "file"
  ],
  [
    "src/api/_idivmod.js",
    "file/src/api/_idivmod.js.html",
    "src/api/_idivmod.js",
    "file"
  ],
  [
    "src/api/add.js",
    "file/src/api/add.js.html",
    "src/api/add.js",
    "file"
  ],
  [
    "src/api/iadd.js",
    "file/src/api/iadd.js.html",
    "src/api/iadd.js",
    "file"
  ],
  [
    "src/api/index.js",
    "file/src/api/index.js.html",
    "src/api/index.js",
    "file"
  ],
  [
    "src/api/mul.js",
    "file/src/api/mul.js.html",
    "src/api/mul.js",
    "file"
  ],
  [
    "src/core/arithmetic/add/_add.js",
    "file/src/core/arithmetic/add/_ADD.js.html",
    "src/core/arithmetic/add/_ADD.js",
    "file"
  ],
  [
    "src/core/arithmetic/add/_iadd.js",
    "file/src/core/arithmetic/add/_IADD.js.html",
    "src/core/arithmetic/add/_IADD.js",
    "file"
  ],
  [
    "src/core/arithmetic/add/_increment.js",
    "file/src/core/arithmetic/add/_increment.js.html",
    "src/core/arithmetic/add/_increment.js",
    "file"
  ],
  [
    "src/core/arithmetic/add/index.js",
    "file/src/core/arithmetic/add/index.js.html",
    "src/core/arithmetic/add/index.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_div_limb_with_prefix.js",
    "file/src/core/arithmetic/div/_div_limb_with_prefix.js.html",
    "src/core/arithmetic/div/_div_limb_with_prefix.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_dc.js",
    "file/src/core/arithmetic/div/_idivmod_dc.js.html",
    "src/core/arithmetic/div/_idivmod_dc.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_dc_21.js",
    "file/src/core/arithmetic/div/_idivmod_dc_21.js.html",
    "src/core/arithmetic/div/_idivmod_dc_21.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_dc_32.js",
    "file/src/core/arithmetic/div/_idivmod_dc_32.js.html",
    "src/core/arithmetic/div/_idivmod_dc_32.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_limb.js",
    "file/src/core/arithmetic/div/_idivmod_limb.js.html",
    "src/core/arithmetic/div/_idivmod_limb.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_limb_with_prefix.js",
    "file/src/core/arithmetic/div/_idivmod_limb_with_prefix.js.html",
    "src/core/arithmetic/div/_idivmod_limb_with_prefix.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_schoolbook.js",
    "file/src/core/arithmetic/div/_idivmod_schoolbook.js.html",
    "src/core/arithmetic/div/_idivmod_schoolbook.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_schoolbook_large_divisor.js",
    "file/src/core/arithmetic/div/_idivmod_schoolbook_large_divisor.js.html",
    "src/core/arithmetic/div/_idivmod_schoolbook_large_divisor.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_schoolbook_subroutine.js",
    "file/src/core/arithmetic/div/_idivmod_schoolbook_subroutine.js.html",
    "src/core/arithmetic/div/_idivmod_schoolbook_subroutine.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_idivmod_slow.js",
    "file/src/core/arithmetic/div/_idivmod_slow.js.html",
    "src/core/arithmetic/div/_idivmod_slow.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/_mod_limb.js",
    "file/src/core/arithmetic/div/_mod_limb.js.html",
    "src/core/arithmetic/div/_mod_limb.js",
    "file"
  ],
  [
    "src/core/arithmetic/div/index.js",
    "file/src/core/arithmetic/div/index.js.html",
    "src/core/arithmetic/div/index.js",
    "file"
  ],
  [
    "src/core/arithmetic/gcd/_euclidean_algorithm.js",
    "file/src/core/arithmetic/gcd/_euclidean_algorithm.js.html",
    "src/core/arithmetic/gcd/_euclidean_algorithm.js",
    "file"
  ],
  [
    "src/core/arithmetic/gcd/_extended_euclidean_algorithm.js",
    "file/src/core/arithmetic/gcd/_extended_euclidean_algorithm.js.html",
    "src/core/arithmetic/gcd/_extended_euclidean_algorithm.js",
    "file"
  ],
  [
    "src/core/arithmetic/gcd/index.js",
    "file/src/core/arithmetic/gcd/index.js.html",
    "src/core/arithmetic/gcd/index.js",
    "file"
  ],
  [
    "src/core/arithmetic/index.js",
    "file/src/core/arithmetic/index.js.html",
    "src/core/arithmetic/index.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/_imul_limb.js",
    "file/src/core/arithmetic/mul/_imul_limb.js.html",
    "src/core/arithmetic/mul/_imul_limb.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/_karatsuba.js",
    "file/src/core/arithmetic/mul/_karatsuba.js.html",
    "src/core/arithmetic/mul/_karatsuba.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/_mul.js",
    "file/src/core/arithmetic/mul/_mul.js.html",
    "src/core/arithmetic/mul/_mul.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/_mul_limb.js",
    "file/src/core/arithmetic/mul/_mul_limb.js.html",
    "src/core/arithmetic/mul/_mul_limb.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/_schoolbook_mul.js",
    "file/src/core/arithmetic/mul/_schoolbook_mul.js.html",
    "src/core/arithmetic/mul/_schoolbook_mul.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/_toom22.js",
    "file/src/core/arithmetic/mul/_toom22.js.html",
    "src/core/arithmetic/mul/_toom22.js",
    "file"
  ],
  [
    "src/core/arithmetic/mul/index.js",
    "file/src/core/arithmetic/mul/index.js.html",
    "src/core/arithmetic/mul/index.js",
    "file"
  ],
  [
    "src/core/arithmetic/pow/_powd.js",
    "file/src/core/arithmetic/pow/_powd.js.html",
    "src/core/arithmetic/pow/_powd.js",
    "file"
  ],
  [
    "src/core/arithmetic/pow/index.js",
    "file/src/core/arithmetic/pow/index.js.html",
    "src/core/arithmetic/pow/index.js",
    "file"
  ],
  [
    "src/core/arithmetic/sub/_decrement.js",
    "file/src/core/arithmetic/sub/_decrement.js.html",
    "src/core/arithmetic/sub/_decrement.js",
    "file"
  ],
  [
    "src/core/arithmetic/sub/_isub.js",
    "file/src/core/arithmetic/sub/_isub.js.html",
    "src/core/arithmetic/sub/_isub.js",
    "file"
  ],
  [
    "src/core/arithmetic/sub/_sub.js",
    "file/src/core/arithmetic/sub/_sub.js.html",
    "src/core/arithmetic/sub/_sub.js",
    "file"
  ],
  [
    "src/core/arithmetic/sub/index.js",
    "file/src/core/arithmetic/sub/index.js.html",
    "src/core/arithmetic/sub/index.js",
    "file"
  ],
  [
    "src/core/array/_alloc.js",
    "file/src/core/array/_alloc.js.html",
    "src/core/array/_alloc.js",
    "file"
  ],
  [
    "src/core/array/_build.js",
    "file/src/core/array/_build.js.html",
    "src/core/array/_build.js",
    "file"
  ],
  [
    "src/core/array/_copy.js",
    "file/src/core/array/_copy.js.html",
    "src/core/array/_copy.js",
    "file"
  ],
  [
    "src/core/array/_fill.js",
    "file/src/core/array/_fill.js.html",
    "src/core/array/_fill.js",
    "file"
  ],
  [
    "src/core/array/_reset.js",
    "file/src/core/array/_reset.js.html",
    "src/core/array/_reset.js",
    "file"
  ],
  [
    "src/core/array/_zeros.js",
    "file/src/core/array/_zeros.js.html",
    "src/core/array/_zeros.js",
    "file"
  ],
  [
    "src/core/array/index.js",
    "file/src/core/array/index.js.html",
    "src/core/array/index.js",
    "file"
  ],
  [
    "src/core/compare/_cmp.js",
    "file/src/core/compare/_CMP.js.html",
    "src/core/compare/_CMP.js",
    "file"
  ],
  [
    "src/core/compare/_cmp_n.js",
    "file/src/core/compare/_CMP_n.js.html",
    "src/core/compare/_CMP_n.js",
    "file"
  ],
  [
    "src/core/compare/_cmp.js",
    "file/src/core/compare/_cmp.js.html",
    "src/core/compare/_cmp.js",
    "file"
  ],
  [
    "src/core/compare/_eq.js",
    "file/src/core/compare/_eq.js.html",
    "src/core/compare/_eq.js",
    "file"
  ],
  [
    "src/core/compare/_ge.js",
    "file/src/core/compare/_ge.js.html",
    "src/core/compare/_ge.js",
    "file"
  ],
  [
    "src/core/compare/_gt.js",
    "file/src/core/compare/_gt.js.html",
    "src/core/compare/_gt.js",
    "file"
  ],
  [
    "src/core/compare/_jz.js",
    "file/src/core/compare/_jz.js.html",
    "src/core/compare/_jz.js",
    "file"
  ],
  [
    "src/core/compare/_le.js",
    "file/src/core/compare/_le.js.html",
    "src/core/compare/_le.js",
    "file"
  ],
  [
    "src/core/compare/_lt.js",
    "file/src/core/compare/_lt.js.html",
    "src/core/compare/_lt.js",
    "file"
  ],
  [
    "src/core/compare/_ne.js",
    "file/src/core/compare/_ne.js.html",
    "src/core/compare/_ne.js",
    "file"
  ],
  [
    "src/core/compare/index.js",
    "file/src/core/compare/index.js.html",
    "src/core/compare/index.js",
    "file"
  ],
  [
    "src/core/convert/_chr.js",
    "file/src/core/convert/_chr.js.html",
    "src/core/convert/_chr.js",
    "file"
  ],
  [
    "src/core/convert/_convert.js",
    "file/src/core/convert/_convert.js.html",
    "src/core/convert/_convert.js",
    "file"
  ],
  [
    "src/core/convert/_convert_slow.js",
    "file/src/core/convert/_convert_slow.js.html",
    "src/core/convert/_convert_slow.js",
    "file"
  ],
  [
    "src/core/convert/_convert_to_larger.js",
    "file/src/core/convert/_convert_to_larger.js.html",
    "src/core/convert/_convert_to_larger.js",
    "file"
  ],
  [
    "src/core/convert/_convert_to_larger_fast.js",
    "file/src/core/convert/_convert_to_larger_fast.js.html",
    "src/core/convert/_convert_to_larger_fast.js",
    "file"
  ],
  [
    "src/core/convert/_convert_to_smaller.js",
    "file/src/core/convert/_convert_to_smaller.js.html",
    "src/core/convert/_convert_to_smaller.js",
    "file"
  ],
  [
    "src/core/convert/_convert_to_smaller_fast.js",
    "file/src/core/convert/_convert_to_smaller_fast.js.html",
    "src/core/convert/_convert_to_smaller_fast.js",
    "file"
  ],
  [
    "src/core/convert/_int.js",
    "file/src/core/convert/_int.js.html",
    "src/core/convert/_int.js",
    "file"
  ],
  [
    "src/core/convert/_log.js",
    "file/src/core/convert/_log.js.html",
    "src/core/convert/_log.js",
    "file"
  ],
  [
    "src/core/convert/_to_string.js",
    "file/src/core/convert/_to_string.js.html",
    "src/core/convert/_to_string.js",
    "file"
  ],
  [
    "src/core/convert/_trim_positive.js",
    "file/src/core/convert/_trim_positive.js.html",
    "src/core/convert/_trim_positive.js",
    "file"
  ],
  [
    "src/core/convert/convert.js",
    "file/src/core/convert/convert.js.html",
    "src/core/convert/convert.js",
    "file"
  ],
  [
    "src/core/convert/convert_keep_zeros.js",
    "file/src/core/convert/convert_keep_zeros.js.html",
    "src/core/convert/convert_keep_zeros.js",
    "file"
  ],
  [
    "src/core/convert/index.js",
    "file/src/core/convert/index.js.html",
    "src/core/convert/index.js",
    "file"
  ],
  [
    "src/core/convert/parse.js",
    "file/src/core/convert/parse.js.html",
    "src/core/convert/parse.js",
    "file"
  ],
  [
    "src/core/convert/parse_keep_zeros.js",
    "file/src/core/convert/parse_keep_zeros.js.html",
    "src/core/convert/parse_keep_zeros.js",
    "file"
  ],
  [
    "src/core/convert/stringify.js",
    "file/src/core/convert/stringify.js.html",
    "src/core/convert/stringify.js",
    "file"
  ],
  [
    "src/core/convert/stringify_keep_zeros.js",
    "file/src/core/convert/stringify_keep_zeros.js.html",
    "src/core/convert/stringify_keep_zeros.js",
    "file"
  ],
  [
    "src/core/convert/translate.js",
    "file/src/core/convert/translate.js.html",
    "src/core/convert/translate.js",
    "file"
  ],
  [
    "src/core/convert/trim_natural.js",
    "file/src/core/convert/trim_natural.js.html",
    "src/core/convert/trim_natural.js",
    "file"
  ],
  [
    "src/core/index.js",
    "file/src/core/index.js.html",
    "src/core/index.js",
    "file"
  ],
  [
    "src/core/thresholds/division.js",
    "file/src/core/thresholds/division.js.html",
    "src/core/thresholds/division.js",
    "file"
  ],
  [
    "src/core/thresholds/index.js",
    "file/src/core/thresholds/index.js.html",
    "src/core/thresholds/index.js",
    "file"
  ],
  [
    "src/core/thresholds/multiplication.js",
    "file/src/core/thresholds/multiplication.js.html",
    "src/core/thresholds/multiplication.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]